server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: "patient-information"
          uri: ${PAT_INFO_URI:http://localhost:8080}
        - id: "patient-history"
          uri: ${PAT_HISTORY_URI:http://localhost:8081}
        - id: "patient-assessment"
          uri: ${PAT_ASSESS_URI:http://localhost:8082}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:5173/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Authorization"
              - "*"
            allowCredentials: true

  application:
    name: gateway


  data:
    mongodb:
      host: localhost
      port: 27017
      database: medi_labo_solution_bdd

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

