version: '3.8'

services:
  app:
    build: .
    container_name: patient_information
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/medi_labo_solution_bdd
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: medi_labo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: